export const pokeActionTypes = {
    GET_POKEMON: 'GET_POKEMON',
    GET_POKEMON_DATA: 'GET_POKEMON_DATA',
    RESET_POKEMON_DATA: 'RESET_POKEMON_DATA',
    STORE_POKEMON_DATA: 'STORE_POKEMON_DATA'
} as const;